import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';

function getImageName(cwd: string, server: string): string {
    const pkgPath = path.join(cwd, 'package.json');
    if (fs.existsSync(pkgPath)) {
        try {
            const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
            if (typeof pkg.name === 'string' && pkg.name) {
                return `${pkg.name}-${server}`;
            }
        } catch { /* ignore */ }
    }
    return server;
}

export function generateDockerfile(server: string, opts?: { lambdaAdapter?: boolean }): string {
    const adapterStage = opts?.lambdaAdapter
        ? `FROM public.ecr.aws/awsguru/aws-lambda-adapter:1.0.0 AS adapter\n\n`
        : '';
    const adapterCopy = opts?.lambdaAdapter
        ? `COPY --from=adapter /lambda-adapter /opt/extensions/lambda-adapter\n\n`
        : '';
    const adapterEnv = opts?.lambdaAdapter ? `ENV AWS_LAMBDA_EXEC_WRAPPER=""\n` : '';

    return `# Generated by morphis docker:build — do not commit this file directly.
${adapterStage}FROM oven/bun:1-alpine

${adapterCopy}WORKDIR /app

# Install production dependencies
COPY package.json bun.lockb* ./
RUN bun install --production --frozen-lockfile 2>/dev/null || bun install --production

# Copy the pre-built bundle
COPY dist/${server}/ ./dist/${server}/
COPY .env.${server} .env.${server}

RUN sed -i 's/^PORT=.*/PORT=8080/' .env.${server}

ENV PORT=8080
${adapterEnv}
EXPOSE 8080

CMD ["bun", "--env-file=.env.${server}", "dist/${server}/index.js"]
`;
}

export async function runDockerBuild(args: string[]): Promise<string> {
    const serverArg = args.find(a => a.startsWith('--server='));
    const versionArg = args.find(a => a.startsWith('--version='));
    const noBuild = args.includes('--no-build');
    const lambdaAdapter = args.includes('--lambda');

    const server = serverArg?.split('=')[1];
    const version = versionArg?.split('=')[1] ?? 'latest';

    if (!server) {
        console.error(chalk.red('\n  Missing required option: --server=<name>\n'));
        process.exit(1);
    }

    const cwd = process.cwd();
    const imageName = getImageName(cwd, server);
    const fullTag = `${imageName}:${version}`;

    // Step 1: build the JS bundle unless skipped
    if (!noBuild) {
        console.log(chalk.cyan(`\n  [docker:build] Building "${server}" server bundle...\n`));
        const scriptsDir = import.meta.dirname;
        await new Promise<void>((resolve) => {
            const buildProc = spawn('bun', [path.join(scriptsDir, 'build.ts'), `--server=${server}`], {
                stdio: 'inherit',
                cwd,
                shell: process.platform === 'win32',
            });
            buildProc.on('exit', (code) => {
                if (code !== 0) process.exit(code ?? 1);
                resolve();
            });
            buildProc.on('error', (err) => {
                console.error(chalk.red(`  Build failed: ${err.message}`));
                process.exit(1);
            });
        });
    }

    // Step 2: verify the bundle exists
    const distEntry = path.join(cwd, 'dist', server, 'index.js');
    if (!fs.existsSync(distEntry)) {
        console.error(chalk.red(`\n  Built entry not found: dist/${server}/index.js`));
        console.error(chalk.gray(`  Run: morphis build --server=${server}\n`));
        process.exit(1);
    }

    // Step 3: write a temporary Dockerfile
    const dockerfilePath = path.join(cwd, `.Dockerfile.morphis.${server}`);

    // If including the Lambda Web Adapter, authenticate to public ECR first
    if (lambdaAdapter) {
        console.log(chalk.cyan(`\n  [docker:build] Authenticating to public ECR for Lambda Web Adapter ...\n`));
        const { execSync } = await import('child_process');
        let token = '';
        try {
            token = execSync('aws ecr-public get-login-password --region us-east-1', {
                encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'],
            }).trim();
        } catch {
            console.error(chalk.red('  Failed to get public ECR token.'));
            console.error(chalk.gray('  Ensure the AWS CLI is configured and you have ecr-public:GetAuthorizationToken permission.\n'));
            process.exit(1);
        }
        await new Promise<void>((resolve) => {
            const login = spawn('docker', ['login', '--username', 'AWS', '--password-stdin', 'public.ecr.aws'], {
                stdio: ['pipe', 'inherit', 'inherit'], cwd, shell: process.platform === 'win32',
            });
            login.stdin.write(token);
            login.stdin.end();
            login.on('exit', (code) => {
                if (code !== 0) { console.error(chalk.red('  docker login to public ECR failed.\n')); process.exit(1); }
                resolve();
            });
            login.on('error', (err) => {
                console.error(chalk.red(`  docker login failed: ${err.message}\n`));
                process.exit(1);
            });
        });
    }

    fs.writeFileSync(dockerfilePath, generateDockerfile(server, { lambdaAdapter }), 'utf8');

    // Step 4: docker build
    console.log(chalk.cyan(`\n  [docker:build] Building image ${chalk.bold(fullTag)} ...\n`));
    await new Promise<void>((resolve) => {
        const proc = spawn('docker', ['build', '--platform=linux/amd64', '--sbom=false', '--provenance=false', '--load', '-f', dockerfilePath, '-t', fullTag, '.'], {
            stdio: 'inherit',
            cwd,
            shell: process.platform === 'win32',
        });
        proc.on('exit', (code) => {
            fs.existsSync(dockerfilePath) && fs.unlinkSync(dockerfilePath);
            if (code !== 0) process.exit(code ?? 1);
            resolve();
        });
        proc.on('error', (err) => {
            fs.existsSync(dockerfilePath) && fs.unlinkSync(dockerfilePath);
            console.error(chalk.red(`  docker build failed: ${err.message}`));
            console.error(chalk.gray('  Ensure Docker is installed and running.'));
            process.exit(1);
        });
    });

    console.log(chalk.green(`\n  [docker:build] Image ready: ${chalk.bold(fullTag)}\n`));
    return fullTag;
}
