import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';
import { getEnvFileName, resolveEnvTarget } from '../utils/env';

const COMPILED_BINARY_TARGET = 'bun-linux-x64';

function getPackageName(cwd: string): string | null {
    const pkgPath = path.join(cwd, 'package.json');
    if (fs.existsSync(pkgPath)) {
        try {
            const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
            if (typeof pkg.name === 'string' && pkg.name) {
                return pkg.name;
            }
        } catch { /* ignore */ }
    }
    return null;
}

function getImageName(cwd: string, server: string, envName?: string | null): string {
    const packageName = getPackageName(cwd);
    if (packageName) {
        const envSuffix = envName ? `-${envName}` : '';
        return `${packageName}-${server}${envSuffix}`;
    }
    return envName ? `${server}-${envName}` : server;
}

function getDockerEntryFileName(server: string): string {
    return `.morphis.docker-entry.${server}.ts`;
}

function createDockerEntrySource(server: string, envFile: string): string {
    return `import router from './src/routes/${server}';

const envFilePath = '${envFile}';
const envResource = Bun.file(envFilePath);

if (await envResource.exists()) {
    const envContent = await envResource.text();
    for (const rawLine of envContent.split(/\r?\n/)) {
        const line = rawLine.trim();
        if (!line || line.startsWith('#')) continue;

        const normalized = line.startsWith('export ') ? line.slice(7).trim() : line;
        const separatorIndex = normalized.indexOf('=');
        if (separatorIndex <= 0) continue;

        const key = normalized.slice(0, separatorIndex).trim();
        if (!key || process.env[key] !== undefined) continue;

        const rawValue = normalized.slice(separatorIndex + 1).trim();
        const quoted = (rawValue.startsWith('"') && rawValue.endsWith('"')) || (rawValue.startsWith("'") && rawValue.endsWith("'"));
        process.env[key] = quoted ? rawValue.slice(1, -1) : rawValue;
    }
}

const port = Number(process.env.PORT ?? 3000);
Bun.serve({
    port,
    reusePort: process.env.MULTI_THREAD === 'true',
    fetch: router.handle.bind(router),
});
console.log(\`Service running on http://localhost:\${port}\`);
`;
}

export function generateDockerfile(server: string, opts?: { envFile?: string; lambdaAdapter?: boolean; port?: number; entryFile?: string; binaryName?: string; compileTarget?: string }): string {
    const adapterStage = opts?.lambdaAdapter
        ? `FROM public.ecr.aws/awsguru/aws-lambda-adapter:1.0.0 AS adapter\n\n`
        : '';
    const adapterCopy = opts?.lambdaAdapter
        ? `COPY --from=adapter /lambda-adapter /opt/extensions/lambda-adapter\n\n`
        : '';
    const adapterEnv = opts?.lambdaAdapter ? `ENV AWS_LAMBDA_EXEC_WRAPPER=""\n` : '';
    const port = opts?.port ?? 8080;
    const envFile = opts?.envFile ?? getEnvFileName(server);
    const entryFile = opts?.entryFile ?? getDockerEntryFileName(server);
    const binaryName = opts?.binaryName ?? server;
    const compileTarget = opts?.compileTarget ?? COMPILED_BINARY_TARGET;

    return `# Generated by morphis docker:build — do not commit this file directly.
${adapterStage}FROM oven/bun:1 AS builder

WORKDIR /app

# Install dependencies before copying the rest of the project for better layer reuse
COPY package.json bun.lockb* ./
RUN bun install --production --frozen-lockfile 2>/dev/null || bun install --production

# Copy the project and compile the selected server into a single binary
COPY . .
RUN bun build --compile --target=${compileTarget} ./${entryFile} --outfile ./${binaryName}

FROM gcr.io/distroless/cc-debian12 AS release

${adapterCopy}WORKDIR /app

# Copy the compiled binary and runtime config only
COPY --from=builder /app/${binaryName} ./${binaryName}
COPY --from=builder /app/${envFile} ./${envFile}

ENV PORT=${port}
${adapterEnv}
EXPOSE ${port}

ENTRYPOINT ["/app/${binaryName}"]
`;
}

export async function runDockerBuild(args: string[]): Promise<string> {
    const versionArg = args.find(a => a.startsWith('--version='));
    const noBuild = args.includes('--no-build');
    const lambdaAdapter = args.includes('--lambda');
    const version = versionArg?.split('=')[1] ?? 'latest';
    const cwd = process.cwd();
    const target = resolveEnvTarget(args, cwd);

    if (!target) {
        console.error(chalk.red('\n  Missing required option: --server=<name>, --env=<name>, or --env-file=.env.<name>\n'));
        process.exit(1);
    }

    if ((args.some(arg => arg.startsWith('--env=')) || args.some(arg => arg.startsWith('--env-file='))) && !fs.existsSync(target.envFilePath)) {
        console.error(chalk.red(`\n  Env file not found: ${target.envFile}\n`));
        process.exit(1);
    }

    const { envFile, envName, server } = target;
    const imageName = getImageName(cwd, server, envName);
    const fullTag = `${imageName}:${version}`;
    const routesFile = path.join(cwd, 'src', 'routes', `${server}.ts`);
    const dockerfilePath = path.join(cwd, `.Dockerfile.morphis.${server}`);
    const entryFile = getDockerEntryFileName(server);
    const entryFilePath = path.join(cwd, entryFile);

    if (!fs.existsSync(routesFile)) {
        console.error(chalk.red(`\n  Routes file not found: src/routes/${server}.ts`));
        console.error(chalk.gray(`  Create src/routes/${server}.ts and export a default Router.\n`));
        process.exit(1);
    }

    if (!noBuild) {
        console.log(chalk.cyan(`\n  [docker:build] Preparing single-binary build for "${server}"...\n`));
    }

    fs.writeFileSync(entryFilePath, createDockerEntrySource(server, envFile), 'utf8');

    if (lambdaAdapter) {
        console.log(chalk.cyan(`\n  [docker:build] Authenticating to public ECR for Lambda Web Adapter ...\n`));
        const { execSync } = await import('child_process');
        let token = '';
        try {
            token = execSync('aws ecr-public get-login-password --region us-east-1', {
                encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'],
            }).trim();
        } catch {
            console.error(chalk.red('  Failed to get public ECR token.'));
            console.error(chalk.gray('  Ensure the AWS CLI is configured and you have ecr-public:GetAuthorizationToken permission.\n'));
            process.exit(1);
        }
        await new Promise<void>((resolve) => {
            const login = spawn('docker', ['login', '--username', 'AWS', '--password-stdin', 'public.ecr.aws'], {
                stdio: ['pipe', 'inherit', 'inherit'], cwd, shell: process.platform === 'win32',
            });
            login.stdin.write(token);
            login.stdin.end();
            login.on('exit', (code) => {
                if (code !== 0) { console.error(chalk.red('  docker login to public ECR failed.\n')); process.exit(1); }
                resolve();
            });
            login.on('error', (err) => {
                console.error(chalk.red(`  docker login failed: ${err.message}\n`));
                process.exit(1);
            });
        });
    }

    fs.writeFileSync(dockerfilePath, generateDockerfile(server, { envFile, lambdaAdapter, entryFile, compileTarget: COMPILED_BINARY_TARGET }), 'utf8');

    console.log(chalk.cyan(`\n  [docker:build] Building image ${chalk.bold(fullTag)} ...\n`));
    await new Promise<void>((resolve) => {
        const proc = spawn('docker', ['build', '--platform=linux/amd64', '--sbom=false', '--provenance=false', '--load', '-f', dockerfilePath, '-t', fullTag, '.'], {
            stdio: 'inherit',
            cwd,
            shell: process.platform === 'win32',
        });
        proc.on('exit', (code) => {
            fs.existsSync(dockerfilePath) && fs.unlinkSync(dockerfilePath);
            fs.existsSync(entryFilePath) && fs.unlinkSync(entryFilePath);
            if (code !== 0) process.exit(code ?? 1);
            resolve();
        });
        proc.on('error', (err) => {
            fs.existsSync(dockerfilePath) && fs.unlinkSync(dockerfilePath);
            fs.existsSync(entryFilePath) && fs.unlinkSync(entryFilePath);
            console.error(chalk.red(`  docker build failed: ${err.message}`));
            console.error(chalk.gray('  Ensure Docker is installed and running.'));
            process.exit(1);
        });
    });

    console.log(chalk.green(`\n  [docker:build] Image ready: ${chalk.bold(fullTag)}\n`));
    return fullTag;
}
